import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import Navbar from "./components/Navbar"

// import {Toaster} from "react-hot-toast"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vani-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={inter.className}>
      <div className="flex flex-col min-h-screen bg-[#373636]">  
      <Navbar />
      {/* <Toaster /> */}
      {children} </div> </body>
    </html>
  );
}
